apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: b77atu9qz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:c62cfc17ebae1b6a1e6de75430425a24cb20f9ba@sha256:e933daa903e4eb518ec8897102d1c2c99509b545e4acb91bf1145d1cb0e9f5ea
          name: container-image
